#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
#Redis Configuration
  redis:
    database: 0
    host: 192.168.37.10
    port: 6379
#    password: toor
#  freemarker:
#    suffix: .ftl